version: "3"

services:

  plone:
    image: plone/plone-backend:6
    ports:
    - "8080:8080"
    volumes:
    - ./:/app/src/eea.api.redirector
    environment:
      ZOPE_FORM_MEMORY_LIMIT: '250MB'
      SECURITY_POLICY_IMPLEMENTATION: "C"
      VERBOSE_SECURITY: "off"
      DEFAULT_ZPUBLISHER_ENCODING: "utf-8"
      DEBUG_MODE: "off"
      ZODB_CACHE_SIZE: "50000"
      SITE: "Plone"
      PROFILES: "eea.api.redirector:default"
      DEVELOP: "/app/src/eea.api.redirector"
      REDIS_SERVER: "redis"
      REDIS_PORT: "6379"
      REDIS_DB: "0"
      REDIS_TIMEOUT: "5"
    depends_on:
    - redis
    # tty: true
    # stdin_open: true
    # command: cat
    # # -- Uncomment the lines above to get an interactive shell into the container --
    # # -- Then run the following commands to start Plone manually: --
    # # docker-compose exec plone bash
    # # ./docker-entrypoint.sh start

  redis:
    image: redis:7.4.7-alpine
    ports:
    - "6379:6379"
    command:
    - "redis-server"
    - "--appendonly yes"
    volumes:
    - redis_data:/data

volumes:
  redis_data: {}
